// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/grpc/storage/v1/storage.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_InitiateUploadDocument_FullMethodName = "/storage.StorageService/InitiateUploadDocument"
	StorageService_CompleteUploadDocument_FullMethodName = "/storage.StorageService/CompleteUploadDocument"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// STORAGE SERVICE DEFINITION
type StorageServiceClient interface {
	InitiateUploadDocument(ctx context.Context, in *InitiateUploadDocumentRequest, opts ...grpc.CallOption) (*InitiateUploadDocumentResponse, error)
	CompleteUploadDocument(ctx context.Context, in *CompleteUploadDocumentRequest, opts ...grpc.CallOption) (*CompleteUploadDocumentResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) InitiateUploadDocument(ctx context.Context, in *InitiateUploadDocumentRequest, opts ...grpc.CallOption) (*InitiateUploadDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateUploadDocumentResponse)
	err := c.cc.Invoke(ctx, StorageService_InitiateUploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CompleteUploadDocument(ctx context.Context, in *CompleteUploadDocumentRequest, opts ...grpc.CallOption) (*CompleteUploadDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadDocumentResponse)
	err := c.cc.Invoke(ctx, StorageService_CompleteUploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// STORAGE SERVICE DEFINITION
type StorageServiceServer interface {
	InitiateUploadDocument(context.Context, *InitiateUploadDocumentRequest) (*InitiateUploadDocumentResponse, error)
	CompleteUploadDocument(context.Context, *CompleteUploadDocumentRequest) (*CompleteUploadDocumentResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) InitiateUploadDocument(context.Context, *InitiateUploadDocumentRequest) (*InitiateUploadDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateUploadDocument not implemented")
}
func (UnimplementedStorageServiceServer) CompleteUploadDocument(context.Context, *CompleteUploadDocumentRequest) (*CompleteUploadDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUploadDocument not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_InitiateUploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateUploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).InitiateUploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_InitiateUploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).InitiateUploadDocument(ctx, req.(*InitiateUploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CompleteUploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CompleteUploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CompleteUploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CompleteUploadDocument(ctx, req.(*CompleteUploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateUploadDocument",
			Handler:    _StorageService_InitiateUploadDocument_Handler,
		},
		{
			MethodName: "CompleteUploadDocument",
			Handler:    _StorageService_CompleteUploadDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/storage/v1/storage.proto",
}
