// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/storage/v1/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,7,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Document) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Document) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Document) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Document) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Document) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PathTokens    []string               `protobuf:"bytes,5,rep,name=path_tokens,json=pathTokens,proto3" json:"path_tokens,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Folder) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetPathTokens() []string {
	if x != nil {
		return x.PathTokens
	}
	return nil
}

func (x *Folder) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Folder) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type InitiateUploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadDocumentRequest) Reset() {
	*x = InitiateUploadDocumentRequest{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadDocumentRequest) ProtoMessage() {}

func (x *InitiateUploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*InitiateUploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateUploadDocumentRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *InitiateUploadDocumentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *InitiateUploadDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiateUploadDocumentRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitiateUploadDocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type InitiateUploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	FormFields    map[string]string      `protobuf:"bytes,3,rep,name=form_fields,json=formFields,proto3" json:"form_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadDocumentResponse) Reset() {
	*x = InitiateUploadDocumentResponse{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadDocumentResponse) ProtoMessage() {}

func (x *InitiateUploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*InitiateUploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *InitiateUploadDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *InitiateUploadDocumentResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitiateUploadDocumentResponse) GetFormFields() map[string]string {
	if x != nil {
		return x.FormFields
	}
	return nil
}

func (x *InitiateUploadDocumentResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CompleteUploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadDocumentRequest) Reset() {
	*x = CompleteUploadDocumentRequest{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadDocumentRequest) ProtoMessage() {}

func (x *CompleteUploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteUploadDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CompleteUploadDocumentRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CompleteUploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadDocumentResponse) Reset() {
	*x = CompleteUploadDocumentResponse{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadDocumentResponse) ProtoMessage() {}

func (x *CompleteUploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_api_grpc_storage_v1_storage_proto protoreflect.FileDescriptor

const file_api_grpc_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"!api/grpc/storage/v1/storage.proto\x12\astorage\"\xb1\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"object_key\x18\a \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rmetadata_json\x18\t \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xc3\x01\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vpath_tokens\x18\x05 \x03(\tR\n" +
	"pathTokens\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x9c\x01\n" +
	"\x1dInitiateUploadDocumentRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\"\xa6\x02\n" +
	"\x1eInitiateUploadDocumentResponse\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.storage.DocumentR\bdocument\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12X\n" +
	"\vform_fields\x18\x03 \x03(\v27.storage.InitiateUploadDocumentResponse.FormFieldsEntryR\n" +
	"formFields\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x1a=\n" +
	"\x0fFormFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x1dCompleteUploadDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"O\n" +
	"\x1eCompleteUploadDocumentResponse\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.storage.DocumentR\bdocument2\xe6\x01\n" +
	"\x0eStorageService\x12i\n" +
	"\x16InitiateUploadDocument\x12&.storage.InitiateUploadDocumentRequest\x1a'.storage.InitiateUploadDocumentResponse\x12i\n" +
	"\x16CompleteUploadDocument\x12&.storage.CompleteUploadDocumentRequest\x1a'.storage.CompleteUploadDocumentResponseB<Z:github.com/a1y/doc-formatter/api/grpc/storage/v1;storagepbb\x06proto3"

var (
	file_api_grpc_storage_v1_storage_proto_rawDescOnce sync.Once
	file_api_grpc_storage_v1_storage_proto_rawDescData []byte
)

func file_api_grpc_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_api_grpc_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_api_grpc_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_storage_v1_storage_proto_rawDesc), len(file_api_grpc_storage_v1_storage_proto_rawDesc)))
	})
	return file_api_grpc_storage_v1_storage_proto_rawDescData
}

var file_api_grpc_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_grpc_storage_v1_storage_proto_goTypes = []any{
	(*Document)(nil),                       // 0: storage.Document
	(*Folder)(nil),                         // 1: storage.Folder
	(*InitiateUploadDocumentRequest)(nil),  // 2: storage.InitiateUploadDocumentRequest
	(*InitiateUploadDocumentResponse)(nil), // 3: storage.InitiateUploadDocumentResponse
	(*CompleteUploadDocumentRequest)(nil),  // 4: storage.CompleteUploadDocumentRequest
	(*CompleteUploadDocumentResponse)(nil), // 5: storage.CompleteUploadDocumentResponse
	nil,                                    // 6: storage.InitiateUploadDocumentResponse.FormFieldsEntry
}
var file_api_grpc_storage_v1_storage_proto_depIdxs = []int32{
	0, // 0: storage.InitiateUploadDocumentResponse.document:type_name -> storage.Document
	6, // 1: storage.InitiateUploadDocumentResponse.form_fields:type_name -> storage.InitiateUploadDocumentResponse.FormFieldsEntry
	0, // 2: storage.CompleteUploadDocumentResponse.document:type_name -> storage.Document
	2, // 3: storage.StorageService.InitiateUploadDocument:input_type -> storage.InitiateUploadDocumentRequest
	4, // 4: storage.StorageService.CompleteUploadDocument:input_type -> storage.CompleteUploadDocumentRequest
	3, // 5: storage.StorageService.InitiateUploadDocument:output_type -> storage.InitiateUploadDocumentResponse
	5, // 6: storage.StorageService.CompleteUploadDocument:output_type -> storage.CompleteUploadDocumentResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpc_storage_v1_storage_proto_init() }
func file_api_grpc_storage_v1_storage_proto_init() {
	if File_api_grpc_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_storage_v1_storage_proto_rawDesc), len(file_api_grpc_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_api_grpc_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_api_grpc_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_api_grpc_storage_v1_storage_proto = out.File
	file_api_grpc_storage_v1_storage_proto_goTypes = nil
	file_api_grpc_storage_v1_storage_proto_depIdxs = nil
}
