// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/storage/v1/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,5,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Document) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Document) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Document) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Document) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// UPLOAD FILE
type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type ListFilesByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesByUserIdRequest) Reset() {
	*x = ListFilesByUserIdRequest{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesByUserIdRequest) ProtoMessage() {}

func (x *ListFilesByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ListFilesByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilesByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListFilesByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesByUserIdResponse) Reset() {
	*x = ListFilesByUserIdResponse{}
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesByUserIdResponse) ProtoMessage() {}

func (x *ListFilesByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ListFilesByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesByUserIdResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_api_grpc_storage_v1_storage_proto protoreflect.FileDescriptor

const file_api_grpc_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"!api/grpc/storage/v1/storage.proto\x12\astorage\"\xca\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1d\n" +
	"\n" +
	"object_key\x18\x05 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x80\x01\n" +
	"\x11UploadFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"C\n" +
	"\x12UploadFileResponse\x12-\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.storage.DocumentR\bdocument\"3\n" +
	"\x18ListFilesByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x19ListFilesByUserIdResponse\x12/\n" +
	"\tdocuments\x18\x01 \x03(\v2\x11.storage.DocumentR\tdocuments2\xb3\x01\n" +
	"\x0eStorageService\x12E\n" +
	"\n" +
	"UploadFile\x12\x1a.storage.UploadFileRequest\x1a\x1b.storage.UploadFileResponse\x12Z\n" +
	"\x11ListFilesByUserId\x12!.storage.ListFilesByUserIdRequest\x1a\".storage.ListFilesByUserIdResponseB<Z:github.com/a1y/doc-formatter/api/grpc/storage/v1;storagepbb\x06proto3"

var (
	file_api_grpc_storage_v1_storage_proto_rawDescOnce sync.Once
	file_api_grpc_storage_v1_storage_proto_rawDescData []byte
)

func file_api_grpc_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_api_grpc_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_api_grpc_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_storage_v1_storage_proto_rawDesc), len(file_api_grpc_storage_v1_storage_proto_rawDesc)))
	})
	return file_api_grpc_storage_v1_storage_proto_rawDescData
}

var file_api_grpc_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_storage_v1_storage_proto_goTypes = []any{
	(*Document)(nil),                  // 0: storage.Document
	(*UploadFileRequest)(nil),         // 1: storage.UploadFileRequest
	(*UploadFileResponse)(nil),        // 2: storage.UploadFileResponse
	(*ListFilesByUserIdRequest)(nil),  // 3: storage.ListFilesByUserIdRequest
	(*ListFilesByUserIdResponse)(nil), // 4: storage.ListFilesByUserIdResponse
}
var file_api_grpc_storage_v1_storage_proto_depIdxs = []int32{
	0, // 0: storage.UploadFileResponse.document:type_name -> storage.Document
	0, // 1: storage.ListFilesByUserIdResponse.documents:type_name -> storage.Document
	1, // 2: storage.StorageService.UploadFile:input_type -> storage.UploadFileRequest
	3, // 3: storage.StorageService.ListFilesByUserId:input_type -> storage.ListFilesByUserIdRequest
	2, // 4: storage.StorageService.UploadFile:output_type -> storage.UploadFileResponse
	4, // 5: storage.StorageService.ListFilesByUserId:output_type -> storage.ListFilesByUserIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_grpc_storage_v1_storage_proto_init() }
func file_api_grpc_storage_v1_storage_proto_init() {
	if File_api_grpc_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_storage_v1_storage_proto_rawDesc), len(file_api_grpc_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_api_grpc_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_api_grpc_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_api_grpc_storage_v1_storage_proto = out.File
	file_api_grpc_storage_v1_storage_proto_goTypes = nil
	file_api_grpc_storage_v1_storage_proto_depIdxs = nil
}
